### ISSUE TITLE
add photos of collaborators to wiki home

### ISSUE THREAD

**Issue by samsammurphy** [samsammurphy/6S_emulator#11]

**Comment by samsammurphy** [comment]
Can you send me a profile pic @daveoloughlin for the wiki home page?

**Comment by daveoloughlin** [comment]
Spent a little more time on the github pages this morning. You've really 
done a lot, especially with the documentation. It's all very helpful. 
The atmospheric correction example is a great introduction to users.
As far as enhancements go, some guidance in choosing an aerosol_profile 
would be useful, for me at least. I assume CO is just the "default". DE 
and MA seem pretty self explanatory? When would you prefer NO? UR would 
be used for NYC? Raleigh?
A couple of more nit-picky things.  The landsat 
<http://landsat.usgs.gov/CDR_LSR.php>link in the README states that L8 
uses an "internal algorithm" as opposed to 4, 5, and 7 which use 6S. I 
think USGS means by that, L8 uses a "modified" implementation of 6S 
which is not validated yet. But it might cause some confusion when users 
look at the link. Maybe a different link would be better, or a small 
footnote? Several of the pages (e.g., iLUTs page 
<https://github.com/samsammurphy/6S_LUT/wiki/Interpolated-Look-up-Tables-%28iLUTs%29>) 
show an "Add a custom footer" button at the bottom while others don't. 
Can that be easily turned off?
Let me know if the JPEG attached doesn't work for any reason.

Dave

**Comment by samsammurphy** [comment]
Thanks Dave!
Have opened up the aerosol guidance idea as an issue, should have that resolved over the next day or two. I have rephrased the README section on Landsat usage of 6S (reasonable?). Will look for 'Add a custom footer' button and remove as necessary.
Cheers,
Sam

**Comment by samsammurphy** [comment]
Oh.. hahaha, that button is only visible to us as contributors. When we sign out and go to the repo the button is not displayed.

**Comment by daveoloughlin** [comment]
Sounds good Sam. Yes, the README looks good.
