### ISSUE TITLE
Move data for look-up tables to separate CSV files.

### ISSUE THREAD

**Issue by suzil** [samsammurphy/6S_emulator#17]
I think it'd be a lot cleaner if we moved these large data tables to separate CSV files and then parsed those files. https://github.com/samsammurphy/6S_emulator/blob/master/bin/astronomical.py#L162 and https://github.com/samsammurphy/6S_emulator/blob/master/bin/astronomical.py#L399

Thoughts?

**Comment by samsammurphy** [comment]
Suzil,

Apologies for delay.

Part of the reason for taking so long was my uncertainty in what the best solution is. My intuition would agree with what you are suggesting (i.e. call up the long, boring, repetitive data in a single command) . However, having seen others source code, especially the original [6S repo](https://github.com/robintw/Py6S) by Robin Wilson, I see the value in keeping the data and the (minimal) code together. The data has to live somewhere. The code is short. And, if there were a problem some where between the two, it would easier to fix.

Closing issue for now. But still open for discussion.

Thanks
Sam
