### ISSUE TITLE
Changing range of valid values?

### ISSUE THREAD

**Issue by jigmegrs** [samsammurphy/6S_emulator#18]
Hi Sam, 

Stumbled upon your useful tool, and was hoping to conveniently be able to use the pre-built LUTs (specifically those for Landsat TM). Thanks for sharing it.

So far I've been happy with the current features, but now have an issue with the range of valid values. According to the the readme, the range of valid WVP values is 0 - 8.5 [g/cm2], and I am dealing with conditions that fall outside this range (~10 [g/cm2]).

If I edited LUT_build.py and tacked on some extra values to the H2O key in the dictionary on line 113, would that extend the range? Would the built table then break, and not work with LUT_interpolate.py anymore?

Regards,
Jigme

**Comment by samsammurphy** [comment]
Hi Jigme,

Should still work without a problem. The LUT_interpolate.py will interpolate what ever set of inputs happen to be defined.

Closing issue for now. If any problems arise lmk and will re-open + try my best to resolve.

Cheers,
Sam
