### ISSUE TITLE
adjacency effect

### ISSUE THREAD

**Issue by joemcglinchy** [samsammurphy/6S_emulator#19]
Hello! Thanks for creating this package. I am using it for LUT based correction of ASTER data. I was wondering, and perhaps this is more accurate to ask of the Py6S package, is there a switch or some capability to enable correction of adjacency effect in the atmospheric correction process? Or is it enabled by default? I can't seem to find any mention of it anywhere in the Py6S code unless it is encoded with the BRDF specification.

Cheers,
Joe

**Comment by samsammurphy** [comment]
It isn't implemented by this emulator but Py6S might have that kind of functionality.

**Comment by samsammurphy** [comment]
closing this issue because it is more of a Py6S issue rather than this of this (simplified) emulator.
